name: Apply vacation

on:
  issues:
    types: [opened, edited]

jobs:
  update-vacation-tracker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Pre Check
      run: |
        # user is in profile
        echo "${{ github.event.issue.body }}" | ./scripts/pre_check.sh

    - name: Update Vacation Tracker
      run: |
          echo "${{ github.event.issue.body }}"  | ./scripts/update_vacation.sh > tmp.yml
          mv tmp.yml vacation.yml

    - name: Post check
      run: |
        # check if they have enough holiday

    - name: update profile
      run: |
          echo "${{ github.event.issue.body }}" | ./scripts/update_profile.sh > tmp.yml
          mv tmp.yml profile.yml


    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: ${{ github.event.issue.title }} apply vacation
        body: "fix #${{ github.event.issue.number }}"
        title: vacation
        branch: "apply-${{ github.event.issue.number }}"
