name: Apply vacation

on:
  issues:
    types: [opened]

jobs:
  update-vacation-tracker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Update Vacation Tracker
      run: |
          body="${{ github.event.issue.body }}" 
          len=$(cat $body | yq 'length')
          if [ "$body" -eq 1 ]; then
            echo 'should have just one key'
            exit 1
          fi 
          
          key=$(cat $body | yq eval 'keys | .[0]')
          body=$( echo $body | yq ea '.dexian |= map (format_datetime("2006-01-02 Monday"))' )

          cat $body | \
          yq ea 'select(fi==0) *+ select(fi==1) // {}' - vacation.yml | \
          yq ea '.[] |= unique' > tmp.yml && mv tmp.yml vacation.yml

    # Step to generate a timestamp for the branch name
    - name: Generate Timestamp for Branch Name
      id: timestamp
      run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: ${{ github.event.issue.title }} apply vacation
        body: "fix #${{ github.event.issue.number }}"
        title: vacation
        branch: "vacation-${{ env.TIMESTAMP }}"
