name: Apply vacation

on:
  issues:
    types: [opened]

jobs:
  update-vacation-tracker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Pre Check
      run: |
        # user is in profile
        body="${{ github.event.issue.body }}" 
        len=$(echo "$body" | yq 'keys | length')
        if [ $len -ne 1 ]; then
          echo 'should have just one key'
          exit 5
        fi 
        key=$( echo "$body" | yq eval 'keys | .[0]' )

        if yq e ".${key}" profile.yml > /dev/null; then
          echo "pre check pass"
        else
          echo "user doesn't exist"
          exit 4
        fi


    - name: Update Vacation Tracker
      run: |
          body="${{ github.event.issue.body }}" 
          len=$(echo "$body" | yq 'keys | length')
          if [ $len -ne 1 ]; then
            echo 'should have just one key'
            exit 5
          fi 
          
          key=$( echo "$body" | yq eval 'keys | .[0]' )
          body=$( echo "$body" | yq ea ".${key} |= map (format_datetime(\"2006-01-02 Monday\"))" )

          echo "$body" | \
          yq ea 'select(fi==0) *+ select(fi==1) // {}' - vacation.yml | \
          yq ea '.[] |= unique' > tmp.yml && mv tmp.yml vacation.yml

    - name: Post check
      run: |
        # check if they have enough holiday

    - name: update profile
      run: |
          key=$( echo "${{ github.event.issue.body }}" | yq eval 'keys | .[0]' )
          updated=$(yq e ".${key}" profile.yml | awk '{print $2}' | cut -d '-' -f1 |  sort | uniq -c | awk '{print $2": "$1}' | yq e "{ \"${key}\": {\"counts\": .} }" -P)
          echo "$updated" | yq ea 'select(fi==0) *+ select(fi==1) // {}' - profile.yml > tmp.yml
          mv tmp.yml profile.yml

    # Step to generate a timestamp for the branch name
    - name: Generate Timestamp for Branch Name
      id: timestamp
      run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: ${{ github.event.issue.title }} apply vacation
        body: "fix #${{ github.event.issue.number }}"
        title: vacation
        branch: "vacation-${{ env.TIMESTAMP }}"
