name: Open PR

on:
  issues:
    types: [opened]

jobs:
  update-vacation-tracker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Update Vacation Tracker
      run: |
        echo ${{ github.event.issue.body }}

